
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Why Tag People? — A quick guide for Teams and other apps</title>
  <meta name="description" content="A simple guide that explains the purpose of tagging in Microsoft Teams and other collaboration apps, with do's, don'ts, and examples." />
  <style>
    :root{
      --bg: #0f172a;          /* slate-900 */
      --panel: #111827;       /* gray-900 */
      --muted: #9ca3af;       /* gray-400 */
      --text: #e5e7eb;        /* gray-200 */
      --brand: #60a5fa;       /* blue-400 */
      --accent: #34d399;      /* emerald-400 */
      --warning: #fbbf24;     /* amber-400 */
      --danger: #f87171;      /* red-400 */
      --ok: #22d3ee;          /* cyan-400 */
      --radius: 16px;
      --shadow: 0 10px 30px rgba(0,0,0,.35);
    }
    *{box-sizing:border-box}
    html,body{margin:0;background:var(--bg);color:var(--text);font:16px/1.6 system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,"Noto Sans","Helvetica Neue",Arial,"Apple Color Emoji","Segoe UI Emoji"}
    a{color:var(--brand);text-decoration:none}
    a:hover{text-decoration:underline}
    .container{max-width:1100px;margin:0 auto;padding:28px}
    header{background:linear-gradient(135deg,rgba(96,165,250,.15),rgba(52,211,153,.12));border-bottom:1px solid rgba(255,255,255,.06)}
    .hero{display:grid;gap:18px;padding:40px 0}
    .title{font-size:clamp(28px,4vw,44px);line-height:1.15;margin:0}
    .subtitle{color:var(--muted);max-width:60ch}
    .card{background:var(--panel);border:1px solid rgba(255,255,255,.06);border-radius:var(--radius);box-shadow:var(--shadow);padding:22px}
    .grid{display:grid;gap:18px}
    @media(min-width:900px){.grid{grid-template-columns:1.2fr 1fr}}
    h2{font-size:clamp(20px,3vw,28px);margin:8px 0 6px}
    h3{font-size:clamp(18px,2.5vw,22px);margin:14px 0 6px}
    ul{padding-left:20px;margin:8px 0}
    li+li{margin-top:6px}
    .tag{display:inline-flex;align-items:center;gap:6px;background:rgba(96,165,250,.15);border:1px solid rgba(96,165,250,.35);color:#cfe6ff;padding:4px 10px;border-radius:999px;font-weight:600}
    .pill{display:inline-block;padding:.2rem .6rem;border-radius:999px;font-size:.85rem;border:1px solid rgba(255,255,255,.08)}
    .pill.good{background:rgba(52,211,153,.14);border-color:rgba(52,211,153,.35)}
    .pill.bad{background:rgba(248,113,113,.14);border-color:rgba(248,113,113,.35)}
    .kbd{font-family:ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;background:#0b1220;border:1px solid rgba(255,255,255,.1);border-bottom-color:rgba(0,0,0,.35);padding:.15rem .4rem;border-radius:6px}
    .toc{display:flex;flex-wrap:wrap;gap:8px}
    .toc a{display:inline-block;background:#0b1220;border:1px solid rgba(255,255,255,.08);padding:.35rem .6rem;border-radius:10px}
    .callout{border-left:4px solid var(--brand);padding:10px 14px;background:rgba(96,165,250,.08);border-radius:10px}
    .examples{display:grid;gap:12px}
    @media(min-width:800px){.examples{grid-template-columns:repeat(2,1fr)}}
    footer{border-top:1px solid rgba(255,255,255,.06);color:var(--muted);padding:22px 0;margin-top:26px}
    .small{font-size:.92rem;color:var(--muted)}
    .checklist li{list-style:none;position:relative;padding-left:26px}
    .checklist li:before{content:"✓";position:absolute;left:0;top:0;color:var(--accent)}
    .xlist li{list-style:none;position:relative;padding-left:26px}
    .xlist li:before{content:"✕";position:absolute;left:0;top:0;color:var(--danger)}
    .caption{font-size:.9rem;color:var(--muted)}
    .mono{font-family:ui-monospace, Menlo, Monaco, Consolas, "Liberation Mono", monospace}
  </style>
</head>
<body>
  <header>
    <div class="container hero">
      <div>
        <p class="tag" aria-label="Tag label">@ Tagging 101</p>
        <h1 class="title">Why tag people and channels?</h1>
        <p class="subtitle">Tagging (like <span class="mono">@name</span>, <span class="mono">@channel</span>, or <span class="mono">#issue</span>) exists to notify the <em>right</em> folks at the <em>right</em> time—so work moves faster without noise. This page explains when to use tags in Microsoft Teams and other apps—and when not to.</p>
      </div>
      <nav class="toc" aria-label="On this page">
        <a href="#what">What is a tag?</a>
        <a href="#why">Why tagging helps</a>
        <a href="#when">When to tag</a>
        <a href="#avoid">When not to tag</a>
        <a href="#how">How to tag (Teams, Slack, Jira, GitHub)</a>
        <a href="#etiquette">Etiquette</a>
        <a href="#faq">Quick FAQ</a>
      </nav>
    </div>
  </header>

  <main class="container grid">
    <section id="what" class="card" aria-labelledby="what-h">
      <h2 id="what-h">What is a tag?</h2>
      <p>Tags are handles you attach to a message, comment, or task to send a targeted notification. Common types:</p>
      <ul>
        <li><strong>Person tags</strong> — <span class="kbd">@Aisha Khan</span> notifies exactly Aisha.</li>
        <li><strong>Group or channel tags</strong> — <span class="kbd">@Payments Team</span> or <span class="kbd">@General</span> notifies everyone in that group or channel.</li>
        <li><strong>Topic / label tags</strong> — <span class="kbd">#oncall</span>, <span class="kbd">#urgent</span> help classify conversations (some tools support these).</li>
      </ul>
      <div class="callout small" role="note"><strong>Purpose:</strong> reduce delays by alerting the smallest relevant audience—no bigger, no smaller.</div>
    </section>

    <section id="why" class="card" aria-labelledby="why-h">
      <h2 id="why-h">Why tagging helps</h2>
      <ul class="checklist">
        <li><strong>Speed:</strong> The right people see it fast without checking every channel.</li>
        <li><strong>Clarity:</strong> The tag shows who owns the next step.</li>
        <li><strong>Focus:</strong> Fewer broad pings = less notification fatigue.</li>
        <li><strong>Traceability:</strong> Decisions and follow-ups are easier to find.</li>
      </ul>
    </section>

    <section id="when" class="card" aria-labelledby="when-h">
      <h2 id="when-h">When to tag</h2>
      <ul class="checklist">
        <li>There is a clear owner or subject‑matter expert for the request.</li>
        <li>Unblocking a task is time‑sensitive or has a dependency.</li>
        <li>You are handing off work or requesting a review/approval.</li>
        <li>You need visibility from a whole team (use a <em>team tag</em>, not everyone).</li>
        <li>An incident or outage requires on‑call attention.</li>
      </ul>
      <p class="caption">Rule of thumb: tag the smallest group that can move the work forward.</p>
    </section>

    <section id="avoid" class="card" aria-labelledby="avoid-h">
      <h2 id="avoid-h">When <em>not</em> to tag</h2>
      <ul class="xlist">
        <li>FYIs that aren’t actionable—post without a tag or use a channel post.</li>
        <li>Asking a question the channel FAQ or docs already answer.</li>
        <li>Using <span class="kbd">@here</span> / <span class="kbd">@channel</span> or <span class="kbd">@Team</span> by default.</li>
        <li>Tagging multiple individuals to “cast a net” (choose one owner; CC the rest without tags).</li>
        <li>Chasing status updates too frequently—batch your questions.</li>
      </ul>
    </section>

    <section id="how" class="card" aria-labelledby="how-h">
      <h2 id="how-h">How to tag in common tools</h2>
      <div class="examples">
        <div>
          <h3>Microsoft Teams</h3>
          <ul>
            <li><strong>Person:</strong> Type <span class="kbd">@</span> then a name → <span class="kbd">@Ravi Patel</span>.</li>
            <li><strong>Tag groups:</strong> Admins/owners can create tag groups (e.g., <span class="kbd">@Android-Devs</span>) and assign members.</li>
            <li><strong>Channels/Teams:</strong> <span class="kbd">@General</span>, <span class="kbd">@Team</span>—use sparingly for announcements.</li>
            <li><strong>Example:</strong> “<span class="mono">@Android-Devs</span> can someone review PR #142 by EOD?”</li>
          </ul>
        </div>
        <div>
          <h3>Slack</h3>
          <ul>
            <li><strong>Person:</strong> <span class="kbd">@name</span>.</li>
            <li><strong>Here / Channel:</strong> <span class="kbd">@here</span> (active now) / <span class="kbd">@channel</span> (everyone) — use rarely.</li>
            <li><strong>User groups:</strong> <span class="kbd">@ios</span>, <span class="kbd">@oncall</span> (workspace admins define these).</li>
            <li><strong>Example:</strong> “<span class="mono">@oncall</span> build failing after deploy. Logs in #deployments.”</li>
          </ul>
        </div>
        <div>
          <h3>Jira</h3>
          <ul>
            <li><strong>Mention:</strong> In comments, type <span class="kbd">@</span> to notify an assignee/reviewer.</li>
            <li><strong>Assignee vs tag:</strong> Prefer setting the <em>Assignee</em> field over tagging multiple people.</li>
            <li><strong>Example:</strong> “Blocking release. <span class="mono">@Priya</span> can you confirm fix version?”</li>
          </ul>
        </div>
        <div>
          <h3>GitHub / GitLab</h3>
          <ul>
            <li><strong>People & teams:</strong> <span class="kbd">@org/team</span>, <span class="kbd">@user</span>.</li>
            <li><strong>Reviews:</strong> Request reviewers instead of tagging many people.</li>
            <li><strong>Example:</strong> “<span class="mono">@org/security</span> please review secrets scanning warnings.”</li>
          </ul>
        </div>
      </div>
    </section>

    <section id="etiquette" class="card" aria-labelledby="etiq-h">
      <h2 id="etiq-h">Tagging etiquette (do this)</h2>
      <ul class="checklist">
        <li><strong>Be specific:</strong> state the ask, the context, and the desired date/time.</li>
        <li><strong>One owner:</strong> tag a single accountable person; list others without tags.</li>
        <li><strong>Batch context:</strong> provide links (docs, tickets, PRs) in the same message.</li>
        <li><strong>Respect time zones:</strong> avoid broad alerts outside working hours.</li>
        <li><strong>Close the loop:</strong> post the resolution so future readers aren’t left guessing.</li>
      </ul>
      <h3>Message templates</h3>
      <ul>
        <li><span class="pill good">Request</span> “<span class="mono">@Owner</span> please approve <a href="#">PR-142</a> by <strong>Today 4 PM</strong> so we can deploy. Context: flake fix.”</li>
        <li><span class="pill good">Heads‑up</span> “Deploy to prod at 17:00 CT. No action needed.”</li>
        <li><span class="pill bad">Don’t</span> “<span class="mono">@everyone</span> thoughts?” (no clear ask)</li>
      </ul>
    </section>

    <section id="faq" class="card" aria-labelledby="faq-h">
      <h2 id="faq-h">Quick FAQ</h2>
      <details>
        <summary><strong>Should I use @Team or @channel?</strong></summary>
        <p>Only for announcements that affect nearly everyone (e.g., outages, policy changes). Otherwise, tag a specific person or user group.</p>
      </details>
      <details>
        <summary><strong>What if I don’t know who to tag?</strong></summary>
        <p>Ask the channel who owns the topic, or check the team wiki/on‑call rota. Tag once you have an owner.</p>
      </details>
      <details>
        <summary><strong>Can tagging replace assignment?</strong></summary>
        <p>No. Use tags to notify; use assignment fields to track responsibility.</p>
      </details>
      <details>
        <summary><strong>How do I reduce noise?</strong></summary>
        <p>Prefer person/user‑group tags over broad alerts, and keep threads focused by replying in‑thread.</p>
      </details>
    </section>
  </main>

  <footer class="container">
    <p class="small">© <span id="y"></span> Tagging 101. Built as a lightweight guide for teams that over‑ping. Customize with your team names and workflows.</p>
  </footer>

  <script>
    // set current year
    document.getElementById('y').textContent = new Date().getFullYear();
  </script>
</body>
</html> 
